apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: yt-downloader
    app.kubernetes.io/instance: yt-downloader
  name: yt-downloader-pvc-downloads
  namespace: yt-downloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "250Mi"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: yt-downloader
    app.kubernetes.io/instance: yt-downloader
  name: yt-downloader-pvc-session
  namespace: yt-downloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: yt-downloader
    app.kubernetes.io/instance: yt-downloader
  name: yt-downloader-pvc-config-root
  namespace: yt-downloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Mi"
